---
title: "Library Tags"
author: "Ivan Jacob Agaloos Pesigan"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Library Tags}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


|                                               |key                                            |annotation                                                                                                                   |keywords                                                                                                                                                                                                    |
|:----------------------------------------------|:----------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|Wright-1918                                    |Wright-1918                                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Wright-1920                                    |Wright-1920                                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Craig-1936                                     |Craig-1936                                     |mediation                                                                                                                    |NULL                                                                                                                                                                                                        |
|Johnson-Neyman-1936                            |Johnson-Neyman-1936                            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Uhlenbeck-Ornstein-1930                        |Uhlenbeck-Ornstein-1930                        |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Wright-1934                                    |Wright-1934                                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Aroian-1947                                    |Aroian-1947                                    |mediation, mediation-delta                                                                                                   |NULL                                                                                                                                                                                                        |
|Cochran-1952                                   |Cochran-1952                                   |robustness                                                                                                                   |NULL                                                                                                                                                                                                        |
|Johnson-Fay-1950                               |Johnson-Fay-1950                               |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Duncan-1969                                    |Duncan-1969                                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Goodman-1960                                   |Goodman-1960                                   |mediation, mediation-delta                                                                                                   |NULL                                                                                                                                                                                                        |
|Granger-1969                                   |Granger-1969                                   |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Kalman-1960                                    |Kalman-1960                                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Alwin-Hauser-1975                              |Alwin-Hauser-1975                              |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Bradley-1978                                   |Bradley-1978                                   |robustness                                                                                                                   |NULL                                                                                                                                                                                                        |
|Cronbach-Furby-1970                            |Cronbach-Furby-1970                            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Efron-1979a                                    |Efron-1979a                                    |NULL                                                                                                                         |bootstrap, discriminant analysis, error rate estimation, jackknife, nonlinear regression, nonparametric variance estimation, resampling, subsample values                                                   |
|Efron-1979b                                    |Efron-1979b                                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Engel-1977                                     |Engel-1977                                     |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Hinkley-1977                                   |Hinkley-1977                                   |regression, regression-hc                                                                                                    |jackknife, linear model, regression, residual, robustness,                                                                                                                                                  |
|Horn-Horn-Duncan-1975                          |Horn-Horn-Duncan-1975                          |regression, regression-hc                                                                                                    |NULL                                                                                                                                                                                                        |
|Nesselroade-Cable-1974                         |Nesselroade-Cable-1974                         |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Osborne-Suddick-1972                           |Osborne-Suddick-1972                           |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Rubin-1976                                     |Rubin-1976                                     |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Arnold-1974                                    |Arnold-1974                                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Baltes-Nesselroade-1979                        |Baltes-Nesselroade-1979                        |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Rogosa-1979                                    |Rogosa-1979                                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Barnard-Collins-Farewell-etal-1981             |Barnard-Collins-Farewell-etal-1981             |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Baron-Kenny-1986                               |Baron-Kenny-1986                               |mediation, mediation-causalsteps                                                                                             |NULL                                                                                                                                                                                                        |
|Bentler-Lee-1983                               |Bentler-Lee-1983                               |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Bollen-1987                                    |Bollen-1987                                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Browne-1984                                    |Browne-1984                                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Chesher-Jewitt-1987                            |Chesher-Jewitt-1987                            |regression, regression-hc                                                                                                    |NULL                                                                                                                                                                                                        |
|Cloninger-1987                                 |Cloninger-1987                                 |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Cox-Klinger-1988                               |Cox-Klinger-1988                               |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Cudeck-1989                                    |Cudeck-1989                                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Efron-1981a                                    |Efron-1981a                                    |NULL                                                                                                                         |bootstrap, jackknife, delta method, nonparametric confidence intervals, nonparametric standard errors                                                                                                       |
|Efron-1981b                                    |Efron-1981b                                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Efron-1987                                     |Efron-1987                                     |NULL                                                                                                                         |resampling methods, approximate confidence intervals, transformations, nonparametric intervals, second-order theory, skewness corrections                                                                   |
|Efron-1988                                     |Efron-1988                                     |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Gollob-Reichardt-1987                          |Gollob-Reichardt-1987                          |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|James-Brett-1984                               |James-Brett-1984                               |mediation, mediation-causalsteps                                                                                             |NULL                                                                                                                                                                                                        |
|Judd-Kenny-1981                                |Judd-Kenny-1981                                |mediation, mediation-causalsteps                                                                                             |NULL                                                                                                                                                                                                        |
|Kaplan-Martin-Robbins-1984                     |Kaplan-Martin-Robbins-1984                     |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Kunsch-1989                                    |Kunsch-1989                                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|MacKinnon-White-1985                           |MacKinnon-White-1985                           |regression, regression-hc                                                                                                    |NULL                                                                                                                                                                                                        |
|McArdle-McDonald-1984                          |McArdle-McDonald-1984                          |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Micceri-1989                                   |Micceri-1989                                   |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Nel-1985                                       |Nel-1985                                       |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Newey-West-1987                                |Newey-West-1987                                |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Rasmussen-1987                                 |Rasmussen-1987                                 |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Rogosa-1980                                    |Rogosa-1980                                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Schenker-1987                                  |Schenker-1987                                  |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Singh-1981                                     |Singh-1981                                     |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Sobel-1982                                     |Sobel-1982                                     |mediation, mediation-delta                                                                                                   |NULL                                                                                                                                                                                                        |
|Sobel-1986                                     |Sobel-1986                                     |mediation, mediation-delta                                                                                                   |NULL                                                                                                                                                                                                        |
|Sobel-1987                                     |Sobel-1987                                     |mediation, mediation-delta                                                                                                   |NULL                                                                                                                                                                                                        |
|Venzon-Moolgavkar-1988                         |Venzon-Moolgavkar-1988                         |NULL                                                                                                                         |confidence intervals, profile likelihood                                                                                                                                                                    |
|White-1980                                     |White-1980                                     |regression, regression-hc                                                                                                    |NULL                                                                                                                                                                                                        |
|Bergstrom-1984                                 |Bergstrom-1984                                 |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Cohen-1988                                     |Cohen-1988                                     |NULL                                                                                                                         |Social sciences--Statistical methods, Probabilities, Statistical power analysis                                                                                                                             |
|NationalResearchCouncil-1982                   |NationalResearchCouncil-1982                   |data                                                                                                                         |NULL                                                                                                                                                                                                        |
|Rubin-1987                                     |Rubin-1987                                     |Lib-Missing-Data-Books                                                                                                       |Multiple imputation (Statistics), Nonresponse (Statistics), Social surveys--Response rate                                                                                                                   |
|Serlin-Lapsley-1985                            |Serlin-Lapsley-1985                            |robustness                                                                                                                   |NULL                                                                                                                                                                                                        |
|Andrews-1991                                   |Andrews-1991                                   |regression, regression-hc                                                                                                    |NULL                                                                                                                                                                                                        |
|Andrews-Monahan-1992                           |Andrews-Monahan-1992                           |regression, regression-hc                                                                                                    |NULL                                                                                                                                                                                                        |
|Bollen-Stine-1990                              |Bollen-Stine-1990                              |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Collins-Wugalter-1992                          |Collins-Wugalter-1992                          |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Cooper-Frone-Russell-etal-1995                 |Cooper-Frone-Russell-etal-1995                 |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Dumenci-Windle-1996                            |Dumenci-Windle-1996                            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Eilers-Marx-1996                               |Eilers-Marx-1996                               |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Kenny-Zautra-1995                              |Kenny-Zautra-1995                              |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Li-Raghunathan-Rubin-1991                      |Li-Raghunathan-Rubin-1991                      |missing, missing-mi                                                                                                          |imputation, missing data, nonresponse, tests of significance                                                                                                                                                |
|Lyapunov-1992                                  |Lyapunov-1992                                  |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|MacKinnon-1994                                 |MacKinnon-1994                                 |mediation-prevention                                                                                                         |Data Interpretation, Statistical; Health Behavior; Humans; Models, Statistical; Primary Prevention, methods; Research Design; Substance-Related Disorders, prevention & control                             |
|Mackinnon-Dwyer-1993                           |Mackinnon-Dwyer-1993                           |mediation-prevention                                                                                                         |NULL                                                                                                                                                                                                        |
|Muthen-Curran-1997                             |Muthen-Curran-1997                             |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Oehlert-1992                                   |Oehlert-1992                                   |NULL                                                                                                                         |approximate moments, asymptotic approximations, Taylor series                                                                                                                                               |
|Oud-vandenBercken-Essers-1990                  |Oud-vandenBercken-Essers-1990                  |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Politis-Romano-1994                            |Politis-Romano-1994                            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Robey-Barcikowski-1992                         |Robey-Barcikowski-1992                         |robustness                                                                                                                   |NULL                                                                                                                                                                                                        |
|Saunders-Assland-Babor-etal-1993               |Saunders-Assland-Babor-etal-1993               |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Schulenberg-OMalley-Bachman-etal-1996          |Schulenberg-OMalley-Bachman-etal-1996          |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Shapiro-Browne-1990                            |Shapiro-Browne-1990                            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Stoffer-Wall-1991                              |Stoffer-Wall-1991                              |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Tibshirani-1996                                |Tibshirani-1996                                |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|VonKorff-Simon-1996                            |VonKorff-Simon-1996                            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Wechsler-Dowdall-Davenport-etal-1995           |Wechsler-Dowdall-Davenport-etal-1995           |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Arbuckle-1996                                  |Arbuckle-1996                                  |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Brockwell-Davis-1991                           |Brockwell-Davis-1991                           |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Collins-Horn-1991                              |Collins-Horn-1991                              |NULL                                                                                                                         |Change (Psychology), Psychometrics                                                                                                                                                                          |
|Davidson-MacKinnon-1993                        |Davidson-MacKinnon-1993                        |regression, regression-hc                                                                                                    |Econometrics                                                                                                                                                                                                |
|Davison-Hinkley-1997                           |Davison-Hinkley-1997                           |bootstrap                                                                                                                    |Bootstrap (Statistics)                                                                                                                                                                                      |
|Efron-Tibshirani-1993                          |Efron-Tibshirani-1993                          |NULL                                                                                                                         |Bootstrap (Statistics)                                                                                                                                                                                      |
|Finkel-1995                                    |Finkel-1995                                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Gollob-Reichardt-1991                          |Gollob-Reichardt-1991                          |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Hamilton-1994                                  |Hamilton-1994                                  |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Harvey-1990                                    |Harvey-1990                                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Kenny-Kashy-Bolger-1998                        |Kenny-Kashy-Bolger-1998                        |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Kim-Nelson-1999                                |Kim-Nelson-1999                                |NULL                                                                                                                         |Economics--Mathematical models, State-space methods, Heteroscedasticity, Sampling (Statistics), Econometrics                                                                                                |
|Ollendick-Prinz-1996                           |Ollendick-Prinz-1996                           |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Robinson-Riley-1999                            |Robinson-Riley-1999                            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Schafer-1997                                   |Schafer-1997                                   |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Wills-Filer-1996                               |Wills-Filer-1996                               |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Andrews-2000                                   |Andrews-2000                                   |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Arnett-2005                                    |Arnett-2005                                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Baker-Piper-McCarthy-etal-2004                 |Baker-Piper-McCarthy-etal-2004                 |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Bauer-Curran-2005                              |Bauer-Curran-2005                              |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Bauer-Preacher-Gil-2006                        |Bauer-Preacher-Gil-2006                        |mediation, mediation-multilevel                                                                                              |multilevel model, hierarchical linear model, indirect effect, mediation, moderated mediation                                                                                                                |
|Bentler-2007                                   |Bentler-2007                                   |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Boker-2002                                     |Boker-2002                                     |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Bolger-Davis-Rafaeli-2003                      |Bolger-Davis-Rafaeli-2003                      |NULL                                                                                                                         |experience sampling method, longitudinal designs, electronic data collection, self-report measures, multilevel models, diary                                                                                |
|Casella-2003                                   |Casella-2003                                   |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Efron-2003                                     |Efron-2003                                     |NULL                                                                                                                         |ABC method, BCA, bootstrap confidence intervals, objective Bayes, plug-in principle                                                                                                                         |
|Davison-Hinkley-Young-2003                     |Davison-Hinkley-Young-2003                     |NULL                                                                                                                         |bagging, bootstrap, conditional inference, empirical strength probability, parametric bootstrap, subsampling, superefficient estimator, tilted distribution, time series, weighted bootstrap                |
|Hall-2003                                      |Hall-2003                                      |NULL                                                                                                                         |block bootstrap, computer-intensive statistics, confidence interval, half-sample, Monte Carlo, moving block, permutation test, resample, resampling, sample survey, statistical experimentation, sub-sample |
|Boos-2003                                      |Boos-2003                                      |NULL                                                                                                                         |confidence intervals, hypothesis testing, resamples, resampling, statistical inference                                                                                                                      |
|Beran-2003                                     |Beran-2003                                     |NULL                                                                                                                         |confidence sets, convolution theorem, double bootstrap, error in coverage probability, local asymptotic equivariance, simultaneous confidence sets                                                          |
|Lele-2003                                      |Lele-2003                                      |NULL                                                                                                                         |model-robust confidence intervals, multiple roots, stochastic processes, Wu's wild bootstrap                                                                                                                |
|Shao-2003                                      |Shao-2003                                      |NULL                                                                                                                         |easy implementation, imputation, robustness, stratification, variance estimation, without replacement sampling                                                                                              |
|Lahiri-2003                                    |Lahiri-2003                                    |NULL                                                                                                                         |imputation, resampling, small-area estimation, survey weights                                                                                                                                               |
|Horowitz-2003                                  |Horowitz-2003                                  |NULL                                                                                                                         |asymptotic distribution, asymptotic refinement, hypothesis test                                                                                                                                             |
|Politis-2003                                   |Politis-2003                                   |NULL                                                                                                                         |block bootstrap, confidence intervals, large sample inference, linear models, nonparametric estimation, resampling, subsampling                                                                             |
|Ernst-Hutson-2003                              |Ernst-Hutson-2003                              |NULL                                                                                                                         |censored data, confidence band, L-estimator, Monte Carlo, order statistics                                                                                                                                  |
|Holmes-2003a                                   |Holmes-2003a                                   |NULL                                                                                                                         |bootstrap, confidence regions, nonpositive curvature, phylogenetic trees                                                                                                                                    |
|Soltis-Soltis-2003                             |Soltis-Soltis-2003                             |NULL                                                                                                                         |bootstrap, jackknife, phylogeny, support                                                                                                                                                                    |
|Holmes-2003b                                   |Holmes-2003b                                   |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Buehlmann-2002                                 |Buehlmann-2002                                 |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Cheong-MacKinnon-Khoo-2003                     |Cheong-MacKinnon-Khoo-2003                     |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Cheung-2007                                    |Cheung-2007                                    |mediation, mediation-delta, mediation-likelihood, mediation-bootstrap                                                        |mediation, bootstrapping                                                                                                                                                                                    |
|Cheung-2008                                    |Cheung-2008                                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Cheung-2009a                                   |Cheung-2009a                                   |mediation, mediation-bootstrap, mediation-likelihood, mediation-delta, mediation-prodclin                                    |mediation analysis, coverage probability, structural equation modeling approach                                                                                                                             |
|Cheung-2009b                                   |Cheung-2009b                                   |mediation, mediation-likelihood                                                                                              |NULL                                                                                                                                                                                                        |
|Cheung-Lau-2007                                |Cheung-Lau-2007                                |mediation, mediation-bootstrap                                                                                               |mediating effects, suppression effects, structural equation modeling                                                                                                                                        |
|Chow-Hamagani-Nesselroade-2007                 |Chow-Hamagani-Nesselroade-2007                 |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Cole-Martin-Steiger-2005                       |Cole-Martin-Steiger-2005                       |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Cole-Maxwell-2003                              |Cole-Maxwell-2003                              |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|CribariNeto-2004                               |CribariNeto-2004                               |regression, regression-hc                                                                                                    |NULL                                                                                                                                                                                                        |
|CribariNeto-daSilva-2010                       |CribariNeto-daSilva-2010                       |regression, regression-hc                                                                                                    |NULL                                                                                                                                                                                                        |
|CribariNeto-Souza-Vasconcellos-2007            |CribariNeto-Souza-Vasconcellos-2007            |regression, regression-hc                                                                                                    |NULL                                                                                                                                                                                                        |
|CribariNeto-Souza-Vasconcellos-2008            |CribariNeto-Souza-Vasconcellos-2008            |regression, regression-hc                                                                                                    |NULL                                                                                                                                                                                                        |
|Fairchild-MacKinnon-Taborga-etal-2009          |Fairchild-MacKinnon-Taborga-etal-2009          |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Ferrer-McArdle-2003                            |Ferrer-McArdle-2003                            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Fritz-MacKinnon-2007                           |Fritz-MacKinnon-2007                           |mediation, mediation-power, mediation-causalsteps, mediation-joint, mediation-delta, mediation-prodclin, mediation-bootstrap |bootstrap, collinearity, mediation analysis, power, tolerance                                                                                                                                               |
|Gatchel-Peng-Peters-etal-2007                  |Gatchel-Peng-Peters-etal-2007                  |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Graham-Olchowski-Gilreath-2007                 |Graham-Olchowski-Gilreath-2007                 |NULL                                                                                                                         |multiple imputation, number of imputations, full information maximum likelihood, missing data, statistical power                                                                                            |
|Grundy-Gondoli-BlodgettSalafia-2007            |Grundy-Gondoli-BlodgettSalafia-2007            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Hamaker-Dolan-Molenaar-2005                    |Hamaker-Dolan-Molenaar-2005                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|HatemiJ-2003                                   |HatemiJ-2003                                   |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|HatemiJ-2004                                   |HatemiJ-2004                                   |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Hayes-2009                                     |Hayes-2009                                     |mediation, mediation-bootstrap                                                                                               |NULL                                                                                                                                                                                                        |
|Hayes-Cai-2007                                 |Hayes-Cai-2007                                 |regression, regression-hc                                                                                                    |NULL                                                                                                                                                                                                        |
|Higgins-Thompson-2002                          |Higgins-Thompson-2002                          |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Kauermann-Carroll-2001                         |Kauermann-Carroll-2001                         |regression, regression-hc                                                                                                    |NULL                                                                                                                                                                                                        |
|Kenny-Korchmaros-Bolger-2003                   |Kenny-Korchmaros-Bolger-2003                   |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Koob-LeMoal-2008                               |Koob-LeMoal-2008                               |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Krull-MacKinnon-2001                           |Krull-MacKinnon-2001                           |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Long-Ervin-2000                                |Long-Ervin-2000                                |regression, regression-hc                                                                                                    |NULL                                                                                                                                                                                                        |
|Ludtke-Marsh-Robitzsch-etal-2008               |Ludtke-Marsh-Robitzsch-etal-2008               |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|MacKinnon-Fritz-Williams-etal-2007             |MacKinnon-Fritz-Williams-etal-2007             |mediation, mediation-prodclin                                                                                                |NULL                                                                                                                                                                                                        |
|MacKinnon-Krull-Lockwood-2000                  |MacKinnon-Krull-Lockwood-2000                  |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|MacKinnon-Lockwood-Hoffman-etal-2002           |MacKinnon-Lockwood-Hoffman-etal-2002           |mediation, mediation-causalsteps, mediation-jointtest, mediation-prodclin                                                    |NULL                                                                                                                                                                                                        |
|MacKinnon-Lockwood-Williams-2004               |MacKinnon-Lockwood-Williams-2004               |mediation, mediation-bootstrap, mediation-montecarlo, mediation-prodclin                                                     |NULL                                                                                                                                                                                                        |
|Maxwell-Cole-2007                              |Maxwell-Cole-2007                              |NULL                                                                                                                         |mediation, direct effect, indirect effect, cross-sectional designs, longitudinal designs                                                                                                                    |
|McArdle-2009                                   |McArdle-2009                                   |NULL                                                                                                                         |linear structural equations, repeated measures                                                                                                                                                              |
|Mehta-Neale-2005                               |Mehta-Neale-2005                               |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Molenaar-2004                                  |Molenaar-2004                                  |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Molenaar-Campbell-2009                         |Molenaar-Campbell-2009                         |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Oud-Jansen-2000                                |Oud-Jansen-2000                                |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Patrick-Maggs-2007                             |Patrick-Maggs-2007                             |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Patrick-Maggs-2009                             |Patrick-Maggs-2009                             |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Peugh-Enders-2004                              |Peugh-Enders-2004                              |NULL                                                                                                                         |EM algorithm, maximum likelihood estimation, missing data, multiple imputation, NORM                                                                                                                        |
|Preacher-Curran-Bauer-2006                     |Preacher-Curran-Bauer-2006                     |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Preacher-Hayes-2004                            |Preacher-Hayes-2004                            |mediation, mediation-delta, mediation-bootstrap                                                                              |life satisfaction, indirect effect, mediation analysis, cognitive therapy, Sobel test                                                                                                                       |
|Preacher-Hayes-2008                            |Preacher-Hayes-2008                            |mediation, mediation-bootstrap                                                                                               |indirect effect, structural equation modeling, residual covariance, total indirect effect, multiple mediator model                                                                                          |
|Raghunathan-Lepkowski-vanHoewyk-etal-2001      |Raghunathan-Lepkowski-vanHoewyk-etal-2001      |NULL                                                                                                                         |item nonresponse, missing at random, multiple imputation, nonignorable missing mechanism, regression, sampling properties and simulations                                                                   |
|Raykov-Marcoulides-2004                        |Raykov-Marcoulides-2004                        |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Reinert-Allen-2007                             |Reinert-Allen-2007                             |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Sakai-MikulichGilbertson-Long-etal-2006        |Sakai-MikulichGilbertson-Long-etal-2006        |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Schafer-Graham-2002                            |Schafer-Graham-2002                            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Selig-Preacher-2009                            |Selig-Preacher-2009                            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Serlin-2000                                    |Serlin-2000                                    |robustness                                                                                                                   |NULL                                                                                                                                                                                                        |
|Shiffman-2009                                  |Shiffman-2009                                  |NULL                                                                                                                         |ecological momentary assessment, substance use, drug use, tobacco, alcohol                                                                                                                                  |
|Shiffman-Stone-Hufford-2008                    |Shiffman-Stone-Hufford-2008                    |NULL                                                                                                                         |diary, experience sampling, real-time data capture                                                                                                                                                          |
|Shrout-Bolger-2002                             |Shrout-Bolger-2002                             |mediation, mediation-bootstrap                                                                                               |NULL                                                                                                                                                                                                        |
|Staudenmayer-Buonaccorsi-2005                  |Staudenmayer-Buonaccorsi-2005                  |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Swift-2000                                     |Swift-2000                                     |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Taylor-MacKinnon-Tein-2007                     |Taylor-MacKinnon-Tein-2007                     |mediation, mediation-bootstrap, mediation-jointtest                                                                          |mediation, bootstrapping                                                                                                                                                                                    |
|vanBuuren-Brand-GroothuisOudshoorn-etal-2006   |vanBuuren-Brand-GroothuisOudshoorn-etal-2006   |NULL                                                                                                                         |multivariate missing data, multiple imputation, distributional compatibility, Gibbs sampling, simulation, proper imputation                                                                                 |
|Wang-Zhang-2020                                |Wang-Zhang-2020                                |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Yuan-Bentler-2000                              |Yuan-Bentler-2000                              |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Yuan-MacKinnon-2009                            |Yuan-MacKinnon-2009                            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Zeileis-2004                                   |Zeileis-2004                                   |regression, regression-hc                                                                                                    |NULL                                                                                                                                                                                                        |
|Zeileis-2006                                   |Zeileis-2006                                   |regression, regression-hc                                                                                                    |NULL                                                                                                                                                                                                        |
|Casella-Berger-2002                            |Casella-Berger-2002                            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Chatfield-2003                                 |Chatfield-2003                                 |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Collins-Sayer-2002                             |Collins-Sayer-2002                             |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Fernandez-2002                                 |Fernandez-2002                                 |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Hektner-Schmidt-Csikszentmihalyi-2007          |Hektner-Schmidt-Csikszentmihalyi-2007          |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Iacus-2008                                     |Iacus-2008                                     |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Lutkepohl-2005                                 |Lutkepohl-2005                                 |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|MacKinnon-2008                                 |MacKinnon-2008                                 |mediation, mediation-book                                                                                                    |Mediation (Statistics)                                                                                                                                                                                      |
|Maggs-Schulenberg-2005                         |Maggs-Schulenberg-2005                         |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Schulenberg-Maggs-OMalley-2003                 |Schulenberg-Maggs-OMalley-2003                 |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Venables-Ripley-2002                           |Venables-Ripley-2002                           |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Babor-HigginsBiddle-Saunders-etal-2001         |Babor-HigginsBiddle-Saunders-etal-2001         |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Aalen-Roysland-Gran-etal-2012                  |Aalen-Roysland-Gran-etal-2012                  |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Aalen-Roysland-Gran-etal-2016                  |Aalen-Roysland-Gran-etal-2016                  |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Antonakis-Bastardoz-Ronkko-2019                |Antonakis-Bastardoz-Ronkko-2019                |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Appelbaum-Cooper-Kline-etal-2018               |Appelbaum-Cooper-Kline-etal-2018               |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Asparouhov-Hamaker-Muthen-2017                 |Asparouhov-Hamaker-Muthen-2017                 |NULL                                                                                                                         |Bayesian methods, dynamic factor analysis, intensive longitudinal data, time series analysis                                                                                                                |
|Asparouhov-Muthen-2018                         |Asparouhov-Muthen-2018                         |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Barker-Taylor-2014                             |Barker-Taylor-2014                             |NULL                                                                                                                         |habit, goal-directed behavior, prefrontal cortex, striatum, alcohol, addiction                                                                                                                              |
|Barnett-2014                                   |Barnett-2014                                   |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Bell-Jones-2014                                |Bell-Jones-2014                                |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Bernardo-Wang-Pesigan-etal-2017                |Bernardo-Wang-Pesigan-etal-2017                |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Biesanz-Falk-Savalei-2010                      |Biesanz-Falk-Savalei-2010                      |mediation, mediation-bootstrap, mediation-bayesian                                                                           |NULL                                                                                                                                                                                                        |
|Blanca-Arnau-LopezMontiel-etal-2013            |Blanca-Arnau-LopezMontiel-etal-2013            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Boettiger-Eddelbuettel-2017                    |Boettiger-Eddelbuettel-2017                    |container, container-docker, container-docker-rocker                                                                         |NULL                                                                                                                                                                                                        |
|Bollen-Brand-2010                              |Bollen-Brand-2010                              |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Bond-Greenfield-Patterson-etal-2014            |Bond-Greenfield-Patterson-etal-2014            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Bou-Satorra-2017                               |Bou-Satorra-2017                               |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Bringmann-Vissers-Wichers-etal-2013            |Bringmann-Vissers-Wichers-etal-2013            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|CastroSchilo-Ferrer-2013                       |CastroSchilo-Ferrer-2013                       |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Chen-Daniel-Ziad-etal-2011                     |Chen-Daniel-Ziad-etal-2011                     |NULL                                                                                                                         |connectivity analysis, vector autoregression (VAR), structural equation modeling (SEM), structural vector autoregression (SVAR)                                                                             |
|Cheung-2013                                    |Cheung-2013                                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Chow-Ho-Hamaker-etal-2010                      |Chow-Ho-Hamaker-etal-2010                      |ild, sem, ssm                                                                                                                |NULL                                                                                                                                                                                                        |
|Chow-Witkiewitz-Grasman-etal-2015              |Chow-Witkiewitz-Grasman-etal-2015              |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Clapp-Madden-Mooney-etal-2017                  |Clapp-Madden-Mooney-etal-2017                  |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Crocetti-Hale-Dimitrova-etal-2014              |Crocetti-Hale-Dimitrova-etal-2014              |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Curran-Bauer-2011                              |Curran-Bauer-2011                              |NULL                                                                                                                         |multilevel modeling, growth modeling, trajectory analysis, within-person effects                                                                                                                            |
|Curran-Howard-Bainter-etal-2014                |Curran-Howard-Bainter-etal-2014                |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Deboeck-Boulton-2016                           |Deboeck-Boulton-2016                           |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Deboeck-Preacher-2015                          |Deboeck-Preacher-2015                          |mediation, mediation-longitudinal                                                                                            |continuous time models, cross-lagged panel model, exact discrete model, longitudinal mediation, mediation                                                                                                   |
|Demeshko-Washio-Kawahara-etal-2015             |Demeshko-Washio-Kawahara-etal-2015             |NULL                                                                                                                         |casual discovery, ARMA models, control theory, AR model, SVAR model, CTVAR model, continuous time linear Markov
system, canonicality, nuclear reactor noise analysis                                         |
|Donamayor-Strelchuk-Baek-etal-2017             |Donamayor-Strelchuk-Baek-etal-2017             |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Driver-Oud-Voelkle-2017                        |Driver-Oud-Voelkle-2017                        |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Driver-Voelkle-2018                            |Driver-Voelkle-2018                            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Dudgeon-2017                                   |Dudgeon-2017                                   |NULL                                                                                                                         |standardized regression coefficients, robust confidence intervals, non-normality                                                                                                                            |
|Eddelbuettel-Balamuta-2017                     |Eddelbuettel-Balamuta-2017                     |r, r-packages                                                                                                                |NULL                                                                                                                                                                                                        |
|Eddelbuettel-Francois-2011                     |Eddelbuettel-Francois-2011                     |r, r-packages                                                                                                                |NULL                                                                                                                                                                                                        |
|Eddelbuettel-Sanderson-2014                    |Eddelbuettel-Sanderson-2014                    |r, r-packages                                                                                                                |NULL                                                                                                                                                                                                        |
|Efron-2012                                     |Efron-2012                                     |NULL                                                                                                                         |deviance, exponential families, generalized linear models, Jeffreys prior                                                                                                                                   |
|Enders-Fairchild-MacKinnon-2013                |Enders-Fairchild-MacKinnon-2013                |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Epskamp-Borsboom-Fried-2017                    |Epskamp-Borsboom-Fried-2017                    |NULL                                                                                                                         |network psychometrics, psychological networks, replicability, bootstrap, tutorial                                                                                                                           |
|Epskamp-Cramer-Waldorp-etal-2012               |Epskamp-Cramer-Waldorp-etal-2012               |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Epskamp-Lourens-Mottus-etal-2018               |Epskamp-Lourens-Mottus-etal-2018               |NULL                                                                                                                         |time-series analysis, multilevel modeling, multivariate analysis, exploratory-data analysis, network modeling                                                                                               |
|Fairchild-MacKinnon-2014                       |Fairchild-MacKinnon-2014                       |mediation-prevention, mediation-moderation                                                                                   |mediation, moderation, prevention research, program evaluation, mechanisms of change, contextual effects                                                                                                    |
|Finlay-Ram-Maggs-etal-2012                     |Finlay-Ram-Maggs-etal-2012                     |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Fritz-Taylor-MacKinnon-2012                    |Fritz-Taylor-MacKinnon-2012                    |mediation, mediation-bootstrap                                                                                               |NULL                                                                                                                                                                                                        |
|Gates-Molenaar-Hillary-etal-2010               |Gates-Molenaar-Hillary-etal-2010               |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Greenfield-Ye-Bond-etal-2014                   |Greenfield-Ye-Bond-etal-2014                   |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Gu-Preacher-Ferrer-2014                        |Gu-Preacher-Ferrer-2014                        |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|HaanRietdijk-Voelkle-Keijsers-Hamaker-2017     |HaanRietdijk-Voelkle-Keijsers-Hamaker-2017     |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Hamaker-Ceulemans-Grasman-etal-2015            |Hamaker-Ceulemans-Grasman-etal-2015            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Hamaker-Kuiper-Grasman-2015                    |Hamaker-Kuiper-Grasman-2015                    |NULL                                                                                                                         |cross-lagged panel, reciprocal effects, longitudinal model, trait-state models, within-person dynamics                                                                                                      |
|Hamaker-Schuurman-Zijlmans-2016                |Hamaker-Schuurman-Zijlmans-2016                |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Hayes-Scharkow-2013                            |Hayes-Scharkow-2013                            |mediation, mediation-bootstrap, mediation-montecarlo, mediation-prodclin                                                     |NULL                                                                                                                                                                                                        |
|Hecht-Voelkle-2019                             |Hecht-Voelkle-2019                             |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Herring-Zamboanga-Olthuis-etal-2016            |Herring-Zamboanga-Olthuis-etal-2016            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Hesterberg-2015                                |Hesterberg-2015                                |NULL                                                                                                                         |bias, confidence intervals, sampling distribution, standard error, statistical concepts, teaching                                                                                                           |
|Hingson-Zha-Smyth-2017                         |Hingson-Zha-Smyth-2017                         |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Hunter-2017                                    |Hunter-2017                                    |ild, ild-software, sem, sem-software, ssm, ssm-software                                                                      |state space model, software, Kalman filter, OpenMx                                                                                                                                                          |
|Jensen-Turk-2014                               |Jensen-Turk-2014                               |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Jones-Waller-2013a                             |Jones-Waller-2013a                             |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Jones-Waller-2015                              |Jones-Waller-2015                              |standardized-regression, standardized-regression-hc                                                                          |NULL                                                                                                                                                                                                        |
|Kazak-2018                                     |Kazak-2018                                     |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Kelley-Preacher-2012                           |Kelley-Preacher-2012                           |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Kenny-Judd-2013                                |Kenny-Judd-2013                                |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|KisbuSakarya-MacKinnon-Miocevic-2014           |KisbuSakarya-MacKinnon-Miocevic-2014           |mediation, mediation-prodclin                                                                                                |NULL                                                                                                                                                                                                        |
|Koopman-Howe-Hollenbeck-etal-2015              |Koopman-Howe-Hollenbeck-etal-2015              |mediation, mediation-bootstrap, mediation-bayesian                                                                           |mediation, bootstrapping, permutation, Bayes                                                                                                                                                                |
|Kossakowski-Groot-Haslbeck-2017                |Kossakowski-Groot-Haslbeck-2017                |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Kuiper-Oisin-2018                              |Kuiper-Oisin-2018                              |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Kuppens-2015                                   |Kuppens-2015                                   |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Kurtzer-Sochat-Bauer-2017                      |Kurtzer-Sochat-Bauer-2017                      |container, container-singularity                                                                                             |NULL                                                                                                                                                                                                        |
|Kwan-Chan-2011                                 |Kwan-Chan-2011                                 |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Kwan-Chan-2014                                 |Kwan-Chan-2014                                 |NULL                                                                                                                         |squared multiple correlation coefficients, structural equation modeling, model reparameterization, multi-sample analysis                                                                                    |
|Lachowicz-Preacher-Kelley-2018                 |Lachowicz-Preacher-Kelley-2018                 |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Leffingwell-Cooney-Murphy-etal-2012            |Leffingwell-Cooney-Murphy-etal-2012            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Levitt-Bamberg-Creswell-etal-2018              |Levitt-Bamberg-Creswell-etal-2018              |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Maxwell-Cole-Mitchell-2011                     |Maxwell-Cole-Mitchell-2011                     |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Merkel-2014                                    |Merkel-2014                                    |container, container-docker                                                                                                  |NULL                                                                                                                                                                                                        |
|Miocevic-Gonzalez-Valente-etal-2017            |Miocevic-Gonzalez-Valente-etal-2017            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Molenaar-2017                                  |Molenaar-2017                                  |NULL                                                                                                                         |Dynamic factor analysis, Granger causality, hybrid models, lagged factorloadings, matrix polynomials, state-space models, vector autoregressive models                                                      |
|Moneta-Chlas-Entner-etal-2011                  |Moneta-Chlas-Entner-etal-2011                  |NULL                                                                                                                         |causal inference, econometric time series, SVAR, graphical causal models, independent component analysis, conditional independence tests                                                                    |
|Neale-Hunter-Pritikin-etal-2015                |Neale-Hunter-Pritikin-etal-2015                |r, r-packages, sem, sem-software                                                                                             |NULL                                                                                                                                                                                                        |
|Northcote-Livingston-2011                      |Northcote-Livingston-2011                      |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|OLaughlin-Martin-Ferrer-2018                   |OLaughlin-Martin-Ferrer-2018                   |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Oravecz-Tuerlinckx-Vandekerckhove-2011         |Oravecz-Tuerlinckx-Vandekerckhove-2011         |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|ORourke-MacKinnon-2018                         |ORourke-MacKinnon-2018                         |mediation-prevention                                                                                                         |NULL                                                                                                                                                                                                        |
|ORourke-MacKinnon-2019                         |ORourke-MacKinnon-2019                         |mediation-prevention                                                                                                         |NULL                                                                                                                                                                                                        |
|Ou-Hunter-Chow-2019                            |Ou-Hunter-Chow-2019                            |ild, ild-software, r, r-packages                                                                                             |NULL                                                                                                                                                                                                        |
|Pastor-Lazowski-2017                           |Pastor-Lazowski-2017                           |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Patrick-TerryMcElrath-2016                     |Patrick-TerryMcElrath-2016                     |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Pesigan-Luyckx-Alampay-2014                    |Pesigan-Luyckx-Alampay-2014                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Piasecki-2019                                  |Piasecki-2019                                  |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Preacher-Kelley-2011                           |Preacher-Kelley-2011                           |mediation-effectsize                                                                                                         |NULL                                                                                                                                                                                                        |
|Preacher-Selig-2012                            |Preacher-Selig-2012                            |mediation, mediation-montecarlo, mediation-bootstrap                                                                         |NULL                                                                                                                                                                                                        |
|Prince-Read-Colder-2019                        |Prince-Read-Colder-2019                        |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Reichardt-2011                                 |Reichardt-2011                                 |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Roache-KarnsWright-Goros-etal-2019             |Roache-KarnsWright-Goros-etal-2019             |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Rosseel-2012                                   |Rosseel-2012                                   |r, r-packages, sem, sem-software                                                                                             |NULL                                                                                                                                                                                                        |
|Sacks-Gonzales-Bouchery-etal-2015              |Sacks-Gonzales-Bouchery-etal-2015              |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Schermerhorn-Chow-Cummings-2010                |Schermerhorn-Chow-Cummings-2010                |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Schouten-Lugtig-Vink-2018                      |Schouten-Lugtig-Vink-2018                      |NULL                                                                                                                         |missing data, multiple imputation, multivariate amputation, evaluation                                                                                                                                      |
|Schultzberg-Muthen-2017                        |Schultzberg-Muthen-2017                        |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Schuurman-Ferrer-deBoerSonnenschein-etal-2016  |Schuurman-Ferrer-deBoerSonnenschein-etal-2016  |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Schuurman-Hamaker-2019                         |Schuurman-Hamaker-2019                         |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Schuurman-Houtveen-Hamaker-2015                |Schuurman-Houtveen-Hamaker-2015                |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Shrout-2011                                    |Shrout-2011                                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Simons-Wills-Emery-etal-2015                   |Simons-Wills-Emery-etal-2015                   |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Singer-2012                                    |Singer-2012                                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Sjoerds-deWit-vandenBrink-etal-2013            |Sjoerds-deWit-vandenBrink-etal-2013            |NULL                                                                                                                         |addiction, fMRI, goal-directed behavior, habit formation, instrumental learning, striatum                                                                                                                   |
|Smith-Juarascio-2019                           |Smith-Juarascio-2019                           |NULL                                                                                                                         |eating disorders, ambulatory assessment, ecological momentary assessment, mHealth, ecological momentary intervention                                                                                        |
|Taylor-MacKinnon-2012                          |Taylor-MacKinnon-2012                          |mediation, mediation-bootstrap                                                                                               |mediation, bootstrapping, permutation, Bayes                                                                                                                                                                |
|Tibshirani-2011                                |Tibshirani-2011                                |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Tofighi-Kelley-2019                            |Tofighi-Kelley-2019                            |mediation, mediation-bayesian, mediation-bootstrap, mediation-likelihood, mediation-montecarlo                               |indirect effect, confidence interval, sequential mediation, Bayesian credible interval                                                                                                                      |
|Tofighi-MacKinnon-2015                         |Tofighi-MacKinnon-2015                         |mediation, mediation-bootstrap, mediation-delta, mediation-montecarlo                                                        |confidence interval, mediation analysis, Monte Carlo                                                                                                                                                        |
|Usami-Murayama-Hamaker-2019                    |Usami-Murayama-Hamaker-2019                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|vanBuuren-GroothuisOudshoorn-2011              |vanBuuren-GroothuisOudshoorn-2011              |NULL                                                                                                                         |MICE, multiple imputation, chained equations, fully conditional specification, Gibbs sampler, predictor selection, passive imputation, R                                                                    |
|VerHoef-2012                                   |VerHoef-2012                                   |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Voelkle-Oud-2012                               |Voelkle-Oud-2012                               |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Voelkle-Oud-Davidov-etal-2012                  |Voelkle-Oud-Davidov-etal-2012                  |NULL                                                                                                                         |continuous time modeling, panel design, autoregressive cross-lagged model, longitudinal data analysis, structural equation modeling                                                                         |
|Vuorre-Bolger-2017                             |Vuorre-Bolger-2017                             |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Wang-2018                                      |Wang-2018                                      |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Wichers-Groot-Psychosystems-2016               |Wichers-Groot-Psychosystems-2016               |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Wu-Jia-2013                                    |Wu-Jia-2013                                    |mediation, mediation-missing, mediation-bootstrap                                                                            |NULL                                                                                                                                                                                                        |
|Yu-Pesigan-Zhang-etal-2019                     |Yu-Pesigan-Zhang-etal-2019                     |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Yu-Wu-Pesigan-2015                             |Yu-Wu-Pesigan-2015                             |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Yuan-Chan-2011                                 |Yuan-Chan-2011                                 |standardized-regression, standardized-regression-delta, standardized-regression-normal, standardized-regression-adf          |asymptotics, bias, consistency, Monte Carlo                                                                                                                                                                 |
|Yzerbyt-Muller-Batailler-etal-2018             |Yzerbyt-Muller-Batailler-etal-2018             |mediation, mediation-jointtest                                                                                               |indirect effects, mediation, joint-significance, bootstrap                                                                                                                                                  |
|Zamboanga-Iwamoto-Pesigan-etal-2015            |Zamboanga-Iwamoto-Pesigan-etal-2015            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Zamboanga-Pesigan-Tomaso-etal-2015             |Zamboanga-Pesigan-Tomaso-etal-2015             |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Zhang-2018                                     |Zhang-2018                                     |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Zhang-Browne-2010                              |Zhang-Browne-2010                              |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Zhang-Ku-Wu-et-al-2019                         |Zhang-Ku-Wu-et-al-2019                         |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Zhang-Pesigan-Kahler-etal-2019                 |Zhang-Pesigan-Kahler-etal-2019                 |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Zhang-Wang-2012                                |Zhang-Wang-2012                                |mediation, mediation-missing, mediation-bootstrap                                                                            |mediation analysis, missing data, MI, TS-ML, bootstrap, auxiliary variables                                                                                                                                 |
|Zyphur-Allison-Tay-etal-2019                   |Zyphur-Allison-Tay-etal-2019                   |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Zyphur-Voelkle-Tay-etal-2019                   |Zyphur-Voelkle-Tay-etal-2019                   |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Bolger-Laurenceau-2013                         |Bolger-Laurenceau-2013                         |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Cheung-2015                                    |Cheung-2015                                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Deboeck-Preacher-Cole-2018                     |Deboeck-Preacher-Cole-2018                     |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Eddelbuettel-2013                              |Eddelbuettel-2013                              |r, r-packages                                                                                                                |NULL                                                                                                                                                                                                        |
|Enders-2010                                    |Enders-2010                                    |NULL                                                                                                                         |Social sciences--Statistical methods, Missing observations (Statistics), Social sciences--Research--Methodology                                                                                             |
|Flor-Turk-2011                                 |Flor-Turk-2011                                 |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Koopman-Howe-Hollenbeck-2014                   |Koopman-Howe-Hollenbeck-2014                   |mediation, mediation-delta, mediation-bootstrap                                                                              |NULL                                                                                                                                                                                                        |
|Kreiss-Lahiri-2012                             |Kreiss-Lahiri-2012                             |NULL                                                                                                                         |bootstrap methods, discrete Fourier transform, linear and nonlinear time series, long range dependence, Markov chains, resampling, second order correctness, stochastic processes                           |
|Little-Rubin-2019                              |Little-Rubin-2019                              |NULL                                                                                                                         |Mathematical statistics, Mathematical statistics--Problems, exercises, etc., Missing observations (Statistics), Missing observations (Statistics)--Problems, exercises, etc.                                |
|Mehl-Conner-Csikszentmihalyi-2011              |Mehl-Conner-Csikszentmihalyi-2011              |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Millsap-2011                                   |Millsap-2011                                   |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Oravecz-Wood-Ram-2018                          |Oravecz-Wood-Ram-2018                          |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Oud-Delsing-2010                               |Oud-Delsing-2010                               |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Pawitan-2013                                   |Pawitan-2013                                   |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Ryan-Kuiper-Hamaker-2018                       |Ryan-Kuiper-Hamaker-2018                       |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Shumway-Stoffer-2017                           |Shumway-Stoffer-2017                           |NULL                                                                                                                         |Time-series analysis, Time-series analysis--Data processing, R (Computer program language)                                                                                                                  |
|Turk-Monarch-2018                              |Turk-Monarch-2018                              |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|vanBuuren-2018                                 |vanBuuren-2018                                 |NULL                                                                                                                         |Multivariate analysis, Multiple imputation (Statistics), Missing observations (Statistics)                                                                                                                  |
|vanMontfort-Oud-Satorra-2010                   |vanMontfort-Oud-Satorra-2010                   |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|vanMontfort-Oud-Voelkle-2018                   |vanMontfort-Oud-Voelkle-2018                   |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Zhang-Wang-Tong-2015                           |Zhang-Wang-Tong-2015                           |mediation, mediation-missing, mediation-bootstrap                                                                            |mediation analysis, missing data, multiple imputation, bootstrap                                                                                                                                            |
|Hesterberg-2014                                |Hesterberg-2014                                |NULL                                                                                                                         |teaching, bootstrap, permutation test, randomization test                                                                                                                                                   |
|Jones-Waller-2013b                             |Jones-Waller-2013b                             |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Muthen-Muthen-2017                             |Muthen-Muthen-2017                             |sem, sem-software                                                                                                            |NULL                                                                                                                                                                                                        |
|Adolf-Loossens-Tuerlinckx-etal-2021            |Adolf-Loossens-Tuerlinckx-etal-2021            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Ash-Gueorguieva-Barnett-etal-2022              |Ash-Gueorguieva-Barnett-etal-2022              |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Bakk-Kuha-2020                                 |Bakk-Kuha-2020                                 |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Cheung-2021                                    |Cheung-2021                                    |NULL                                                                                                                         |heterogeneity, gold standard, outcome variable, datasets, mediation analysis                                                                                                                                |
|Cheung-Cheung-Lau-etal-2022                    |Cheung-Cheung-Lau-etal-2022                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Cheung-Pesigan-2023a                           |Cheung-Pesigan-2023a                           |NULL                                                                                                                         |influential cases, outliers, structural equation modeling, AMOS, sensitivity analysis, SPSS                                                                                                                 |
|Cheung-Pesigan-2023b                           |Cheung-Pesigan-2023b                           |r, r-packages, sem, sem-software, sem-likelihood                                                                             |confidence interval, likelihood-based confidence interval, robust method, structural equation modeling                                                                                                      |
|Cheung-Pesigan-Vong-2022                       |Cheung-Pesigan-Vong-2022                       |NULL                                                                                                                         |bootstrapping, effect sizes, confidence intervals                                                                                                                                                           |
|Courtney-Russell-2021                          |Courtney-Russell-2021                          |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|DeMartini-Gueorguieva-Taylor-etal-2022         |DeMartini-Gueorguieva-Taylor-etal-2022         |NULL                                                                                                                         |alcohol, alcohol habit, Bayesian modeling, habit learning, heavy drinking                                                                                                                                   |
|Didier-King-Polley-etal-2023                   |Didier-King-Polley-etal-2023                   |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Dora-Piccirillo-Foster-etal-2023               |Dora-Piccirillo-Foster-etal-2023               |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Driver-2025                                    |Driver-2025                                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Fridberg-Wang-Porges-2022                      |Fridberg-Wang-Porges-2022                      |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Georgeson-AlvarezBartolo-MacKinnon-2023        |Georgeson-AlvarezBartolo-MacKinnon-2023        |mediation                                                                                                                    |mediation, cross-sectional mediation, sensitivity analysis                                                                                                                                                  |
|Gunn-Steingrimsson-Merrill-etal-2021           |Gunn-Steingrimsson-Merrill-etal-2021           |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Hamaker-Muthen-2020                            |Hamaker-Muthen-2020                            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Hecht-Zitzmann-2020a                           |Hecht-Zitzmann-2020a                           |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Hecht-Zitzmann-2020b                           |Hecht-Zitzmann-2020b                           |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Hecht-Zitzmann-2021                            |Hecht-Zitzmann-2021                            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Lee-Gates-2023                                 |Lee-Gates-2023                                 |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Li-Oravecz-Zhou-etal-2022                      |Li-Oravecz-Zhou-etal-2022                      |bayesian, ild                                                                                                                |Bayesian zero-inflated Poisson model, forecast, intensive longitudinal data, regime-switching, spatial data, substance use                                                                                  |
|Li-Wood-Ji-etal-2021                           |Li-Wood-Ji-etal-2021                           |NULL                                                                                                                         |multilevel vector autoregressive models, Bayesian modeling, missing data, affective dynamics                                                                                                                |
|Lohmann-Zitzmann-Voelkle-etal-2022             |Lohmann-Zitzmann-Voelkle-etal-2022             |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Loossens-Mestdagh-Dejonckheere-etal-2020       |Loossens-Mestdagh-Dejonckheere-etal-2020       |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Loossens-Tuerlinckx-Verdonck-2021              |Loossens-Tuerlinckx-Verdonck-2021              |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Manthey-Hassan-Carr-etal-2021                  |Manthey-Hassan-Carr-etal-2021                  |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|McKendrick-Graziane-2020                       |McKendrick-Graziane-2020                       |NULL                                                                                                                         |conditioned place preference, CPP, drug reward, addiction-like behavior, drugs of abuse, substance use disorder, addiction, rodent model                                                                    |
|McNeish-Hamaker-2020                           |McNeish-Hamaker-2020                           |NULL                                                                                                                         |dynamic structural equation modeling, time-series analysis, intensive longitudinal data, multilevel modeling                                                                                                |
|McNeish-MacKinnon-2025                         |McNeish-MacKinnon-2025                         |mediation, mediation-longitudinal                                                                                            |intensive longitudinal data, time-series, mediation, EMA, daily diary                                                                                                                                       |
|Mulder-2022                                    |Mulder-2022                                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Mulder-Hamaker-2020                            |Mulder-Hamaker-2020                            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Muthen-Asparouhov-2022                         |Muthen-Asparouhov-2022                         |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Norman-Peacock-Ferguson-etal-2020              |Norman-Peacock-Ferguson-etal-2020              |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Nust-Eddelbuettel-Bennett-etal-2020            |Nust-Eddelbuettel-Bennett-etal-2020            |container, container-docker, container-rocker                                                                                |NULL                                                                                                                                                                                                        |
|Oh-Hunter-Chow-2025                            |Oh-Hunter-Chow-2025                            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Orth-Clark-Donnellan-etal-2021                 |Orth-Clark-Donnellan-etal-2021                 |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Orzek-Voelkle-2023                             |Orzek-Voelkle-2023                             |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Park-Chow-Epskamp-etal-2024                    |Park-Chow-Epskamp-etal-2024                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Park-Fisher-Chow-etal-2023a                    |Park-Fisher-Chow-etal-2023a                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Park-Fisher-Chow-etal-2023b                    |Park-Fisher-Chow-etal-2023b                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Pesigan-Cheung-2020                            |Pesigan-Cheung-2020                            |mediation, mediation-likelihood, mediation-bootstrap, mediation-montecarlo                                                   |mediation, nonnormal, confidence interval, structural equation modeling, bootstrapping                                                                                                                      |
|Pesigan-Cheung-2023                            |Pesigan-Cheung-2023                            |mediation, mediation-missing, mediation-bootstrap, mediation-montecarlo, mediation-jointtest, sem, r, r-packages             |Monte Carlo method, nonparametric bootstrap, indirect effect, mediation, missing completely at random, missing at random, full-information maximum likelihood, multiple imputation                          |
|Pesigan-Russell-Chow-2025a                     |Pesigan-Russell-Chow-2025a                     |NULL                                                                                                                         |mediation, effect size, continuous-time, delta method, Monte Carlo method, parametric bootstrap, regions of significance, R package, cTMed                                                                  |
|Pesigan-Sun-Cheung-2023                        |Pesigan-Sun-Cheung-2023                        |r, r-packages                                                                                                                |standardized regression coefficients, confidence intervals, delta method standard errors, heteroskedasticity-consistent standard errors, R package                                                          |
|Ray-Du-Grodin-etal-2020                        |Ray-Du-Grodin-etal-2020                        |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Rhemtulla-vanBork-Borsboom-2020                |Rhemtulla-vanBork-Borsboom-2020                |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Richards-Barnett-Cook-etal-2022                |Richards-Barnett-Cook-etal-2022                |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Richards-Glenn-Turrisi-etal-2024               |Richards-Glenn-Turrisi-etal-2024               |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Richards-Mallett-Turrisi-etal-2025             |Richards-Mallett-Turrisi-etal-2025             |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Richards-Turrisi-Russell-2024                  |Richards-Turrisi-Russell-2024                  |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Rousselet-Pernet-Wilcox-2021                   |Rousselet-Pernet-Wilcox-2021                   |NULL                                                                                                                         |bootstrap, confidence interval, correlation, R, simulation, trimmed mean, median, reaction time, skewness, group comparison, open materials                                                                 |
|Russell-LindenCarmichael-Lanza-etal-2020       |Russell-LindenCarmichael-Lanza-etal-2020       |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Russell-Richards-Turrisi-etal-2025             |Russell-Richards-Turrisi-etal-2025             |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Russell-Smyth-Turrisi-Rodriguez-2023           |Russell-Smyth-Turrisi-Rodriguez-2023           |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Russell-Turrisi-Smyth-2022                     |Russell-Turrisi-Smyth-2022                     |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Ryan-Hamaker-2021                              |Ryan-Hamaker-2021                              |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Savalei-Rosseel-2021                           |Savalei-Rosseel-2021                           |NULL                                                                                                                         |incomplete data, nonnormal data, robust corrections, software implementation                                                                                                                                |
|Shaygan-Karami-2020                            |Shaygan-Karami-2020                            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Tofighi-Kelley-2020                            |Tofighi-Kelley-2020                            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Usami-2020                                     |Usami-2020                                     |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Usami-2022                                     |Usami-2022                                     |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|vanEgmond-Wright-Livingston-etal-2020          |vanEgmond-Wright-Livingston-etal-2020          |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Zeileis-Koll-Graham-2020                       |Zeileis-Koll-Graham-2020                       |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Chow-Losardo-Park-etal-2023                    |Chow-Losardo-Park-etal-2023                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Gates-Chow-Molenaar-2023                       |Gates-Chow-Molenaar-2023                       |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Hayes-2022                                     |Hayes-2022                                     |mediation, mediation-bootstrap, mediation-book                                                                               |Social sciences--Statistical methods, Mediation (Statistics), Regression analysis                                                                                                                           |
|Vanhasbroeck-Ariens-Tuerlinckx-etal-2021       |Vanhasbroeck-Ariens-Tuerlinckx-etal-2021       |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Arbuckle-2020                                  |Arbuckle-2020                                  |sem, sem-software                                                                                                            |NULL                                                                                                                                                                                                        |
|Arbuckle-2021                                  |Arbuckle-2021                                  |sem, sem-software                                                                                                            |NULL                                                                                                                                                                                                        |
|Asparouhov-Muthen-2022                         |Asparouhov-Muthen-2022                         |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Eddelbuettel-Francois-Allaire-etal-2023        |Eddelbuettel-Francois-Allaire-etal-2023        |r, r-package                                                                                                                 |NULL                                                                                                                                                                                                        |
|Jorgensen-Pornprasertmanit-Schoemann-etal-2022 |Jorgensen-Pornprasertmanit-Schoemann-etal-2022 |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Kurtzer-cclerget-Bauer-etal-2021               |Kurtzer-cclerget-Bauer-etal-2021               |container, container-singularity                                                                                             |NULL                                                                                                                                                                                                        |
|Patrick-Miech-Johnston-etal-2023               |Patrick-Miech-Johnston-etal-2023               |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Pesigan-2022                                   |Pesigan-2022                                   |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|RCoreTeam-2021                                 |RCoreTeam-2021                                 |r, r-manual                                                                                                                  |NULL                                                                                                                                                                                                        |
|RCoreTeam-2022                                 |RCoreTeam-2022                                 |r, r-manual                                                                                                                  |NULL                                                                                                                                                                                                        |
|RCoreTeam-2023                                 |RCoreTeam-2023                                 |r, r-manual                                                                                                                  |NULL                                                                                                                                                                                                        |
|RCoreTeam-2024                                 |RCoreTeam-2024                                 |r, r-manual                                                                                                                  |NULL                                                                                                                                                                                                        |
|RCoreTeam-2025                                 |RCoreTeam-2025                                 |r, r-manual                                                                                                                  |NULL                                                                                                                                                                                                        |
|SAMHSA-2020                                    |SAMHSA-2020                                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|SAMHSA-2023                                    |SAMHSA-2023                                    |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Schulenberg-Patrick-Johnston-etal-2021         |Schulenberg-Patrick-Johnston-etal-2021         |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Tange-2021                                     |Tange-2021                                     |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Tange-2024                                     |Tange-2024                                     |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Waller-2022                                    |Waller-2022                                    |r, r-package                                                                                                                 |NULL                                                                                                                                                                                                        |
|Feitelson-Rudolph-Schwiegelshohn-2003          |Feitelson-Rudolph-Schwiegelshohn-2003          |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Yoo-Jette-Grondona-2003                        |Yoo-Jette-Grondona-2003                        |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Celeux-Soromenho-1996                          |Celeux-Soromenho-1996                          |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Hoogland-Boomsma-1998                          |Hoogland-Boomsma-1998                          |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Flora-Curran-2004                              |Flora-Curran-2004                              |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Nylund-Asparouhov-Muthen-2007                  |Nylund-Asparouhov-Muthen-2007                  |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Yang-2006                                      |Yang-2006                                      |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Hamaker-Nesselroade-Molenaar-2007              |Hamaker-Nesselroade-Molenaar-2007              |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Hershberger-Moskowitz-2002                     |Hershberger-Moskowitz-2002                     |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Nesselroade-McArdle-Aggen-etal-2002            |Nesselroade-McArdle-Aggen-etal-2002            |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Song-Ferrer-2012                               |Song-Ferrer-2012                               |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
|Zhang-Lee-Li-etal-2025                         |Zhang-Lee-Li-etal-2025                         |NULL                                                                                                                         |NULL                                                                                                                                                                                                        |
