name: Docker and Apptainer Build

on:
  workflow_run:
    workflows: [ "Make Project" ]
    types:
      - completed
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - 
        name: Set the environment variables
        run: |
          echo "NOW=$( date '+%F-%H%M%S%2N' )" >> $GITHUB_ENV
          echo "APPTAINER_VERSION=$(curl -s "https://api.github.com/repos/apptainer/apptainer/releases/latest" | grep -Po '"tag_name": "v\K[^"]*')" >> $GITHUB_ENV
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Docker build and push
        uses: docker/build-push-action@v4.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_CONTAINER }}:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_CONTAINER }}:${{ env.NOW }}
      -
        name: Set up Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: ${{ env.APPTAINER_VERSION }}
      -
        name: Build Apptainer container
        run: apptainer build ${{ secrets.DOCKER_HUB_CONTAINER }}.sif docker://${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_CONTAINER }}:${{ env.NOW }}
      -
        name: Run Apptainer container
        run: |
          apptainer exec ${{ secrets.DOCKER_HUB_CONTAINER }}.sif cat /etc/os-release
          apptainer exec ${{ secrets.DOCKER_HUB_CONTAINER }}.sif cat /srv/build/CONTAINER_RELEASE_MSG > release.txt
