name: Build Quarto Website

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Set up Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.1.9
      -
        name: Build Apptainer container
        run: apptainer build image.sif docker://ijapesigan/rocker:latest
      -
        name: Build Project
        run: apptainer exec image.sif make
      -
        name: Render Quarto Project
        run: apptainer exec image.sif make qmd
      -
        name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          clean: true
          branch: quarto
          folder: quarto
