name: R CMD check (nold)

on:
  workflow_run:
    workflows: [ "Make Project" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/r-hub/containers/nold:latest

    steps:
    - uses: actions/checkout@v3

    - uses: r-lib/actions/setup-pandoc@v2

    - name: Install dependencies
      run: |
        R -q -e 'pak::pkg_install(c("deps::.", "any::rcmdcheck"), dependencies = TRUE)'

    - uses: r-lib/actions/check-r-package@v2
