name: R-CMD-check (nold)

on:
  workflow_run:
    workflows: [ "Source Code" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/r-hub/containers/nold:latest

    steps:
    - 
      name: Checkout src repo
      uses: actions/checkout@v3
      with:
        ref: 'src'

    -
      name: Install dependencies
      run: |
        R -q -e 'if (!require("pak")) install.packages("pak")'
        R -q -e 'pak::pkg_install(c("deps::.", "any::rcmdcheck"), dependencies = TRUE)'

    -
      name: R-CMD-check
      uses: r-lib/actions/check-r-package@v2
      with:
        error-on: '"error"'
