name: R CMD check with R-hub containers

on:
  workflow_run:
    workflows: [ "Make Project" ]
    types:
      - completed
    inputs:
      inpcont:
        description: 'Check container'
        required: true
        type: choice
        options:
		    - 'ubuntu-clang'
		    - 'ubuntu-gcc12'
		    - 'ubuntu-next'
		    - 'ubuntu-release'
        - 'atlas'
		    - 'clang-asan'
		    - 'clang16'
		    - 'clang17'
        - 'gcc13'
        - 'nold'
		    - 'valgrind'
		    - 'centos7'

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/r-hub/containers/${{ github.event.inputs.inpcont }}:latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        R -q -e 'pak::pkg_install(c("deps::.", "any::rcmdcheck"), dependencies = TRUE)'
    - uses: r-lib/actions/check-r-package@v2
