name: R CMD check (ubuntu-clang)

on:
  workflow_run:
    workflows: [ "Source Code" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/r-hub/containers/ubuntu-clang:latest

    steps:
    - 
      name: Checkout src repo
      uses: actions/checkout@v3
      with:
        repository: 'ijapesigan/src'

    - 
      name: Set locale
      run: localectl set-locale LANG=en_US.UTF-8

    -
      name: Install dependencies
      run: |
        R -q -e 'if (!require("pak")) install.packages("pak")'
        R -q -e 'pak::pkg_install(c("deps::.", "any::rcmdcheck"), dependencies = TRUE)'

    -
      name: R CMD check
      uses: r-lib/actions/check-r-package@v2
