name: rhub-debian-gcc-patched

on:
  workflow_run:
    workflows: [ "Make Project" ]
    types:
      - completed
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: rhub/debian-gcc-patched
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      USE_BSPM: "true"
      _R_CHECK_FORCE_SUGGESTS_: "false"

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      - 
        name: Install devtools
        run: R -e "install.packages(\"devtools\")"
      - 
        name: devtools::check
        run: R -e "devtools::check()"
      - 
        name: devtools::install
        run: R -e "devtools::install(dependencies = TRUE)"
      - 
        name: devtools::test
        run: R -e "devtools::test()"

