name: Shell Check

on:
  workflow_run:
    workflows: ["Make Project"]
    types:
      - completed

jobs:

  build:
    runs-on: ubuntu-latest

    if: "contains(github.event.head_commit.message, '[AUTO-COMMIT]')"

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
