name: Shell Check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    if: "contains(github.event.head_commit.message, '[AUTO-COMMIT]')"

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
