name: Test Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  test-job:
    name: Test Job
    runs-on: windows-latest
    steps:
    - name: Install winget
      uses: Cyberboss/install-winget@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install R, Rtools, pandoc, and quarto
      run: |
        winget install RProject.R --force --disable-interactivity --accept-source-agreements
        winget install RProject.Rtools --force --disable-interactivity --accept-source-agreements
        winget install JohnMacFarlane.Pandoc --force --disable-interactivity --accept-source-agreements
        winget install RStudio.quarto --force --disable-interactivity --accept-source-agreements

    - name: Test R
      run: Get-Command R
