name: Test Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  test-job:
    name: Test Job
    runs-on: windows-latest
    steps:
    - name: Install R
      run: |
        choco install r.project --params "/AddToPath"

    - name: Test R
      run: R
